# Generated by Django 5.2.8 on 2025-11-12 16:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Provide a name for the workout which describes it concisely and efficiently.', max_length=200)),
                ('rest_time', models.SmallIntegerField(default=90, help_text='In seconds, how much time to rest between sets.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(help_text='The order in sequence of exercises for specified workout.')),
                ('name', models.CharField(help_text='Provide a name for the exercise which is recognizable by you and others.', max_length=200)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout.workout')),
            ],
            options={
                'ordering': ['workout', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SetOfReps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(help_text='The order in sequence of sets for specified exercise.')),
                ('info', models.CharField(help_text='Useful instructions, like weight, intensity, how-to, etc', max_length=200)),
                ('nb_reps', models.SmallIntegerField(help_text='The number of reps to aim for in this set.')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets_of_reps', to='workout.exercise')),
            ],
            options={
                'verbose_name_plural': 'Sets of reps',
                'ordering': ['exercise', 'order'],
                'constraints': [models.UniqueConstraint(fields=('exercise', 'order'), name='unique_order_for_exercise')],
            },
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('workout', 'order'), name='unique_order_for_workout'),
        ),
    ]
